language: java
jdk:
- oraclejdk8
sudo: required

services:
  - docker

script :
  - mvn clean test;

install: true

deploy:
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - mvn clean install dockerfile:push
  on:
    branch: master

cache:
  directories:
  - .autoconf
  - $HOME/.m2

env:
- PACKAGE_VERSION="1.0.*"