language: java
jdk:
- oraclejdk8
sudo: required

services:
  - docker

script :
  - mvn clean test
  branches:
    only:
    - master

install: true

deploy:
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - mvn clean install dockerfile:push
  on:
    branch: feature/2-CI-Improvements

cache:
  directories:
  - .autoconf
  - $HOME/.m2