language: java
jdk:
- oraclejdk8
sudo: required

services:
  - docker

script :
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [[$TRAVIS_BRANCH=="feature/2-CI-Improvements"]]
      then mvn clean install dockerfile:push
    else
      mvn clean test
    fi

#  - if [ $TRAVIS_PULL_REQUEST == false && $TRAVIS_BRANCH == "development" ]; then
#      echo "# Bump version and flyway migrate db";
#    else
#      echo "Skip version increment!";
#    fi

install: true

cache:
  directories:
  - .autoconf
  - $HOME/.m2

env:
- PACKAGE_VERSION="1.0.*"