language: java
jdk:
- oraclejdk8
sudo: required

services:
  - docker

script :
  - if [$TRAVIS_BRANCH == "master" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      mvn clean install dockerfile:push;
    else
      mvn clean install;
    fi

install: true

cache:
  directories:
  - .autoconf
  - $HOME/.m2

env:
- PACKAGE_VERSION="1.0.*"