language: java
jdk:
- oraclejdk8
sudo: required

services:
- docker

script :
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- if [$TRAVIS_BRANCH == "master" ];then
    echo "Building master"
    mvn versions:set -DremoveSnapshot;
    mvn clean install dockerfile:push;
  else
    echo "Building branch"
    mvn test;
  fi

install: true

cache:
  directories:
  - .autoconf
  - $HOME/.m2