language: java
jdk:
- oraclejdk8
sudo: required

services:
- docker

script :
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# mvn clean install dockerfile:push
- echo $TRAVIS_BRANCH
- if [ "$TRAVIS_BRANCH" == "master" ]; mvn clean install; else echo "inside else block"; fi

install: true

cache:
  directories:
  - .autoconf
  - $HOME/.m2