language: java
jdk:
- oraclejdk8
sudo: required

services:
  - docker

if: branch = master
  script :
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - mvn clean install dockerfile:push

script:
  - mvn clean install

install: true

cache:
  directories:
  - .autoconf
  - $HOME/.m2

env:
- PACKAGE_VERSION="1.0.*"